### ISSUE TITLE
`MemoryStorage::list_solutions_pool` returns duplicate values for identical solutions

### ISSUE THREAD

**Issue by supiket** [essential-contributions/essential-server#155]
Came across this bug during this scenario:
1. Deploy an empty but valid solution that solves an empty intent and run the server.
2. Repeat step 1. Note that the solutions have identical hashes.

There are two blocks that each contain one solution, as expected. However, calling `solution_outcome` for this solution returns 3 results:
```
[
SolutionOutcome::Success(0), // 0 is block number here
SolutionOutcome::Success(1),
SolutionOutcome::Success(1)
]
```

The underlying issue here is that inside step 2, `Essential::build_block` calls `Storage::list_solutions_pool` and receives two solutions when it should receive one.

**Comment by freesig** [comment]
@supiket when you get a chance could you check if this is still an issue or close this issue

**Comment by supiket** [comment]
Closed by https://github.com/essential-contributions/essential-server/pull/157
